[[constraint]]
  name = "github.com/monkeydioude/moon"
  version = "1.6.0"

[[constraint]]
  name = "github.com/monkeydioude/tools"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.1.0"
